INSERT INTO USUARIOS (id, email, password, roles) VALUES
(100, 'prueba@alianza.com.co', '$2a$10$xI0lLdrNUxqJJj0ja.TqL.vtx4IjHnrmN7MRbgtZZ8OyLH8.jS8PW', 'CONSULTA_USUARIO,ACTUALIZA_USUARIO');

INSERT INTO USUARIOS (id, email, password, roles) VALUES
(101, 'admin@alianza.com.co', '$2a$10$xI0lLdrNUxqJJj0ja.TqL.vtx4IjHnrmN7MRbgtZZ8OyLH8.jS8PW', 'CONSULTA_USUARIO,ACTUALIZA_USUARIO,ELIMINA_USUARIO,CREAR_USUARIO_BD,CONSULTA_USUARIO_LDAP');